spring.application.name=OffTheCharts

# MariaDB connection information
spring.datasource.url=jdbc:mariadb://localhost:3320/
spring.datasource.username=user
spring.datasource.password=password
# Needed for Case Sensitive Tables and Columns
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.servlet.context-path=/off-the-charts
